package elgatopro300.bbsfbx.mixin;

import mchorse.bbs_mod.cubic.render.CubicCubeRenderer;
import mchorse.bbs_mod.ui.framework.elements.utils.StencilMap;

import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.gen.Accessor;

/**
 * Exposes the protected {@code r/g/b/a}, {@code light}, {@code overlay} and
 * {@code stencilMap} fields of {@code CubicCubeRenderer} -- the superclass of
 * every fork's {@code CubicVAORenderer} -- for use by the per-material
 * {@code renderGroup} intercepts ({@code CubicVAORendererMixinBase} /
 * {@code CubicVAORendererMixinCML}).
 *
 * <p>This is deliberately an {@code @Accessor} mixin targeting
 * {@code CubicCubeRenderer} directly - the class that actually <em>declares</em>
 * the fields - rather than {@code @Shadow}s on {@code CubicVAORenderer} (a
 * subclass that merely inherits them). Shadowing a field declared on a
 * superclass from a mixin targeting the concrete subclass is not reliably
 * resolved by sponge-mixin's field pre-processor (this is exactly what
 * produced the "@Shadow field r was not located in the target class" crash).
 * Pointing the mixin at the declaring class itself sidesteps that resolution
 * path entirely.</p>
 *
 * <p>Any instance of {@code CubicVAORenderer} is also an instance of
 * {@code CubicCubeRenderer}, so {@code (CubicCubeRendererAccessor) (Object) this}
 * inside the renderer mixins is a valid cast -- and, unlike the cached
 * reflection reads it replaces, every access is real generated bytecode with
 * no per-group/per-frame overhead.</p>
 */
@Mixin(value = CubicCubeRenderer.class, remap = false)
public interface CubicCubeRendererAccessor
{
    @Accessor("r")
    float bbsFbx$getR();

    @Accessor("g")
    float bbsFbx$getG();

    @Accessor("b")
    float bbsFbx$getB();

    @Accessor("a")
    float bbsFbx$getA();

    @Accessor("light")
    int bbsFbx$getLight();

    @Accessor("overlay")
    int bbsFbx$getOverlay();

    @Accessor("stencilMap")
    StencilMap bbsFbx$getStencilMap();
}
